### ISSUE TITLE
Link from PyPI to the repo

### ISSUE THREAD

**Issue by szabgab** [Wizock/BlockFrame#1]
Using [Pydigger](https://pydigger.com/search/no-vcs) I monitor recent uploads to PyPI that don't include a link to their VCS. (GitHub/GitLab/etc).  I bumped into https://pypi.org/project/BlockFrame/  I searched for it and found this project. Is this the source of that project? Would you like a PR to add the back-link?

**Comment by Wizock** [comment]
Sure, I was planning to add information on my pypi page for blockframe one version 1.0.0 came out, but sure go for it, I'm sure it will be appreciated.
